### PR TITLE
Biocontainers

### PR DESCRIPTION
**Pull request by hroest**
create zip file for distributable OpenMS

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Great. This should be built for every release?

**Comment by hroest** [comment]
yes we would create this for every release. The corresponding container is 

https://github.com/BioContainers/containers/pull/195

**Comment by hroest** [comment]
@mwalzer maybe we can use this strategy also elsewhere to bring down container size

**Comment by hroest** [comment]
basically the idea is to only store the zip file and use this to create the biodocker container ... 

btw @jpfeuffer somebody should make a new one for 2.3 :-)

**Pull request merged**
