### PR TITLE
Optimize Dockerfiles

### PR DESCRIPTION
**Pull request by radusuciu**
This is a draft PR to optimize the OpenMS dockerfiles. I've moved contrib, library, executable and pyopenms builds into one multi-stage `Dockerfile`.

It can be further optimized (see my work here: https://github.com/radusuciu/docker-openms), but I wanted to submit the PR first to gather comments. I think it would be pretty easy to move this to the main OpenMS repository as well (#28), with just a few modifications to the relevant GitHub Actions workflows.

Potential further optimizations and issues to keep in mind:
- [ ] add a runtime stage which just copies all of the executables and only installs the bare minimum runtime libraries
- [ ] switch to using a debian slim base image
- [ ] clarify use of `OPENMS_BRANCH` and `OPENMS_TAG`. I've opted to use the latter to refer to git tags, not the repository tag
- [ ] pyopenms target isn't building due to missing `python-dev` package. I copied this straight from the original dockerfile so I assume that that must've been broken as well
- [ ] adjust software `LABEL` for each stage
- [ ] workflows in main repo need to be adjusted. this includes the singularity build

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Thank you very much! I am a bit unsure if merging those docker files might have some unwanted implications. @jpfeuffer what is your take on that?

**Comment by radusuciu** [comment]
@poshul I sent you a message via Discord but I think you might not be using the Dockerfile from this PR? There's no boost building stage here (though this is something we can discuss). There is such a stage in my own repo and I'm happy to shed light on that but going to need more context for the error.

@timosachsenberg short answer: you provide a target argument to the build command that tells it which stage to build. Currently the workflow has this step:

```yaml
      - name: Build and Push Docker Library Image
        uses: docker/build-push-action@v3
        with:
          push: true # Will only build if this is not here
          context: dockerfiles/library
          build-args: |
            OPENMS_TAG=latest
            OPENMS_BRANCH=${{ steps.extract_branch.outputs.branch }}
          tags: |
            ghcr.io/${{ steps.downcase_repo.outputs.repo }}-library:${{ steps.tag_name.outputs.tag }}
```

if this PR were merged, we would change the context to just `dockerfiles` and add a `target` parameter. Also, as I noted in the initial PR message, I used `OPENMS_TAG` to mean the tag in the OpenMS repo.. though perhaps I made the wrong choice there. Putting that aside for now, the updated step would look like:

```yaml
      - name: Build and Push Docker Library Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: dockerfiles
          target: library
          build-args: |
            OPENMS_TAG=${{ steps.extract_branch.outputs.branch }}
          tags: |
            ghcr.io/${{ steps.downcase_repo.outputs.repo }}-library:${{ steps.tag_name.outputs.tag }}
```

**Comment by radusuciu** [comment]
Would it be easier if I just opened a PR in the OpenMS/OpenMS repo that moves all Dockerfiles and implements all of the needed workflow changes simultaneously?

**Comment by jpfeuffer** [comment]
Hi! Looks doable in general but I have a question.
We currently build the contrib image in the contrib repo since we also use it as a caching mechanism for CI jobs to save contrib install/building time.
Why would we be building it here again? We definitely should have a way to allow building on top of an existing/pulled contrib. In general, a full Ubuntu system contrib is not a bad idea but it has to be a conscious all-in decision, because once we stop using it for CI it will not be tested and is doomed to break.

BTW: tag is the docker image tag

**Comment by jpfeuffer** [comment]
And yes, moving this to the OpenMS repo would be great!

**Comment by radusuciu** [comment]
>We currently build the contrib image in the contrib repo since we also use it as a caching mechanism for CI jobs to save contrib install/building time. Why would we be building it here again?

This is up to you, I'm not well versed enough in how you've structured things so I'll obviously defer to you on that. I pulled it in here since I saw it as a base for the library build (in my separate project contrib and library are just "openms-build"), but my use-case is focused on using the executables. I figured we could still push a contrib container in separate workflow step with `--target contrib`, keeping the same tags.

> We definitely should have a way to allow building on top of an existing/pulled contrib. In general, a full Ubuntu system contrib is not a bad idea but it has to be a conscious all-in decision, because once we stop using it for CI it will not be tested and is doomed to break.

This is a good point, but I may be a bit confused. From what I saw in that repo, I had the impression that CI doesn't use the docker container that is built there - am I wrong?

> And yes, moving this to the OpenMS repo would be great!

Sounds good, I'll close this draft PR after we've got consensus on how to handle the contrib issue and then can open a new PR that will be a bit closer to something you can consider merging

**Comment by timosachsenberg** [comment]
k let's break this down into smaller steps:
It sounds to me that this Dockerfile could be moved now to the OpenMS/OpenMS repo with an update to https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/containerdeploy.yml
that basically creates compatible same docker/singularity files for library, executables....
I think this would be an improvement to the current state. @jpfeuffer did I miss something? Does this e.g. have influence on how much we can cache?

For the other containers (e.g., those that require manylinux https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/pyopenms-wheels.yml#L280 ). I am not sure what to do. Can we just also move the dockerfile to the main repo?

**Comment by jpfeuffer** [comment]
Hmm but if we put this full build into OpenMS we need a way to check for changes in the contrib submodules and re-trigger since it would not be based on a pre-built contrib image anymore.

Basically:
- if contrib submodule updates: build all versions of a contrib container (system, openms-contrib, manylinux) and everything that depends on it
- if only code in OpenMS updates: use existing contrib containers as base and build the rest

Roughly like that. One needs to think about what happens when a PR is made that updates contrib. Which contrib are you going to use for the CI in this PR, since the new contrib image will not exist yet. Preferably the new one but then the build times get longer since you have to build the contrib before starting the rest of the builds.

Note: The contrib *image* is only used for the pyopenms build (to make sure contrib is at least tested in one configuration). The rest of the CI jobs downloads the contrib binaries (which are built and uploaded for every push to contrib) from our infrastructure.

It will be complex. The easiest would be to get rid of contrib and instead focus on making upstream contributions to package managers to make sure that everything we need is available there and use package managers. Or vcpkg but then you need to cache since e.g. Qt re-builds are infeasible. Conan would be a solution with artifacts stored on our infrastructure. But I am drifting off now and it was discussed many times already with no real consensus.

**Comment by timosachsenberg** [comment]
My personal opinion is that getting rid of the contrib is the way to go for the future (if feasible).
I envision that most times one can just use package managers (which already works for e.g. ubuntu) or - if this is not possible: use vcpkg with Qt using a systems package (https://github.com/OpenMS/OpenMS/pull/7236) . 

The question is: can we get this to work on all platforms?
For Ubuntu we know it works:

Ubuntu:
- [x] system packages
- [x] vcpkg

but what about the others? Can you fill some from your memory? I saw you added something to brew

manylinux2014
- [?] system packages
- [?] vcpkg

Mac AMD64
- [?] system packages / brew
- [?] vcpkg
 
Mac Arm
- [?] system packages / brew
- [?] vcpkg

Windows
- [?] system packages / choco?
- [?] vcpkg

**Comment by jpfeuffer** [comment]
I agree with getting rid of contrib. Should we open a discussion thread somewhere? I can confirm that it works with brew on Intel and Silicon.

@radusuciu Regarding this PR. We could merge it and even move it to the OpenMS repo if it would allow the replacement of the contrib base image. E.g. if the library and the downstream executable dockerfile steps could use an existing contrib instead of depending on a contrib that is built in the same multi-step dockerfile. Then we could just run `docker build --target library --args contrib_base=ghcr.io/OpenMS/contribXYZ` and `docker build --target executable`. Do you know what I mean?

**Comment by jpfeuffer** [comment]
@timosachsenberg An alternative would also be conda(-forge) as a package manager. My PR will expire soon as stale by the way.

**Comment by timosachsenberg** [comment]
@jpfeuffer I moved the contrib discussion to https://github.com/OpenMS/OpenMS/discussions/7302 and agree that @radusuciu can go forward with this PR.

**Comment by radusuciu** [comment]
@jpfeuffer that all makes sense, I'll proceed with moving this PR to the main repo and will check on the linked discussion in case it has any bearing on this

**Comment by radusuciu** [comment]
Closing this in favor of the PR in the main repo: https://github.com/OpenMS/OpenMS/pull/7303

**Pull request closed without merging**
